# Generated by Django 4.0.3 on 2022-03-20 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(default='', max_length=22, verbose_name='名称')),
                ('number', models.IntegerField(default=0, verbose_name='座位数量')),
                ('photo', models.FileField(default='', upload_to='Room/photo/', verbose_name='头像')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='活跃状态')),
            ],
            options={
                'verbose_name_plural': '自习室管理',
                'db_table': 'Room',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(default='', max_length=22, verbose_name='姓名')),
                ('password', models.CharField(default='', max_length=32, verbose_name='密码')),
                ('phone', models.CharField(default='', max_length=11, verbose_name='手机号')),
                ('email', models.CharField(default='', max_length=22, verbose_name='邮箱')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('photo', models.FileField(default='', upload_to='Students/photo/', verbose_name='头像')),
                ('integral', models.IntegerField(default=100, verbose_name='积分')),
                ('is_active', models.BooleanField(default=True, verbose_name='活跃状态')),
            ],
            options={
                'verbose_name_plural': '学生管理',
                'db_table': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('text', models.CharField(default='', max_length=400, verbose_name='主要扣积分内容')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='活跃状态')),
            ],
            options={
                'verbose_name_plural': '提示管理',
                'db_table': 'Text',
            },
        ),
        migrations.CreateModel(
            name='Integrals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('integral', models.IntegerField(default=0, verbose_name='扣积分')),
                ('text', models.CharField(default='', max_length=220, verbose_name='主要扣积分内容')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='活跃状态')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.students', verbose_name='学生')),
            ],
            options={
                'verbose_name_plural': '扣积分管理',
                'db_table': 'Integral',
            },
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('number', models.IntegerField(default=0, verbose_name='预约座位号')),
                ('period', models.IntegerField(default=1, verbose_name='时间段')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='活跃状态')),
                ('students', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.students', verbose_name='学生')),
            ],
            options={
                'verbose_name_plural': '预约管理',
                'db_table': 'Booking',
            },
        ),
    ]
