# Generated by Django 4.0.3 on 2022-03-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_text_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='period',
            field=models.IntegerField(choices=[(1, '上午'), (2, '下午'), (3, '晚自习')], default=1, verbose_name='时间段'),
        ),
    ]
