# Generated by Django 4.0.3 on 2022-03-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_bookings_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='title',
            field=models.CharField(default='', max_length=120, verbose_name='题目'),
        ),
        migrations.AlterField(
            model_name='text',
            name='text',
            field=models.TextField(default='', verbose_name='内容'),
        ),
    ]
