# Generated by Django 4.0.3 on 2022-03-21 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_text_title_alter_text_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='integral',
        ),
    ]
