# Generated by Django 4.0.3 on 2022-03-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_remove_students_integral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrals',
            name='integral',
        ),
        migrations.AddField(
            model_name='integrals',
            name='title',
            field=models.CharField(default='', max_length=220, verbose_name='警告题目'),
        ),
    ]
