# Generated by Django 4.0.3 on 2022-03-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_remove_integrals_integral_integrals_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrals',
            name='text',
            field=models.TextField(default='', max_length=220, verbose_name='警告内容内容'),
        ),
    ]
