# Generated by Django 4.0.3 on 2022-03-21 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_integrals_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.rooms', verbose_name='自习室'),
        ),
    ]
